--- #Bootstrap Webservers
- hosts: testing
  become: yes
  vars:
    target_service: nginx

  tasks:
  - name: Install ngnix
    apt:
     name: "{{ target_service }}"
     update_cache: yes
     force_apt_get: yes
  - name: Make sure nginx is started
    systemd:
     name: "{{ target_service }}"
     state: started
  - name: Creating new html file
    file:
     name: /var/www/html/index2.html
     state: touch
  - name: Add content to web file
    lineinfile:
      line: "<h1>Hey this is a file created with Ansible!!! Information about the machine: <br></br> {{ ansible_distribution }} {{ ansible_distribution_release }}</h1>"
      path: /var/www/html/index2.html
  - name: Check that url is available and return the content
    uri:
      url: http://localhost/index2.html
      return_content: yes
